### ISSUE TITLE
[1.x] Remove dependency on Laravel Breeze

### ISSUE THREAD

**Issue by lphilps** [Laragear/Meta#4]
### PHP & Platform

alll

### Database

all

### Laravel version

9.47.0

### Have you done this?

- [X] I have checked my logs and I'm sure is a bug in this package.
- [X] I can reproduce this bug in isolation (vanilla Laravel install)
- [ ] I can suggest a workaround as a Pull Request

### Expectation

Be able to use Meta, and the Laragear Two Factor package, without pulling Laravel Breeze into my application.

### Description

I installed the Larager Two Factor package, which works really well btw, and it required this package, laragear/meta.

That's all good, but Meta has a requirement in composer.json for laravel/breeze.  I can't see any place in the Meta code that depends on Breeze, and I don't need, use or want Breeze in my application, but if I install Two Factor, or Meta ... I get breeze.

If this is required and I've overlooked the dependency, my apologies, but if not, can the composer dependency on breeze be removed?

### Reproduction

```php
composer require laragear/two-factor
or
composer require laragear/meta

and you'll see laravel/breeze being pulled in.
```

**Comment by DarkGhostHunter** [comment]
I'll update this myself.

**Comment by DarkGhostHunter** [comment]
Done in v1.6.2
