### ISSUE TITLE
[1.x] withMiddleware calls cause user specified middlewarePriority's to be ignored

### ISSUE THREAD

**Issue by lphilps** [Laragear/Meta#5]
### PHP & Platform

all

### Database

all

### Laravel version

9.47.0

### Have you done this?

- [X] I have checked my logs and I'm sure is a bug in this package.
- [X] I can reproduce this bug in isolation (vanilla Laravel install)
- [ ] I can suggest a workaround as a Pull Request

### Expectation

I expect that the middlewarePriority specified in app/Http/Kernel.php will be respected.

### Description

Laravel documents a way to specify the order in which non-global middleware is run:
https://laravel.com/docs/9.x/middleware#sorting-middleware

If you specify this, then install Laragear two-factor, which uses meta to define new middleware, your user specified middleware priority is lost.  I'll confess this is really hard to observe/test, but ...

if you add a `logger($this->middlewarePriority);` call right before the return statement at the end of the `resolveMiddleware` method in `vendor/laravel/framework/src/Illuminate/Routing/Router.php`, then execute a web request and look for the DEBUG line in the log file, you'll see that it is using the middlewarePriority array from the Laravel base class, not the one you specified in `app/Http/Kernel.php` and as a result the middleware is not sorting the way you specified.

The bug appears to be in the `withMiddleware` method in the BootHelpers trait.  It calls `$this->app->make(Kernel::class)` and near the top of the file contains `use Illuminate\Foundation\Http\Kernel` - the base class.

Instead I believe this use statement should be `use Illuminate\Contracts\Http\Kernel` after which the `app->make()` call will resolve to `app/Http/Kernel`.

I hope this makes sense, and if there is a different workaround, I'd be very open to it.

### Reproduction

```php
See the Description.
- Copy the middlewarePriority values from the Illuminate Kernel.php file into your own app/Http/Kernel.php file, then insert one of your own Middleware methods into the middle of the array.
- Add a logger call to `Router::resolveMiddleware` as described above.
- Execute a web request then check the log file and you'll see that the base class version of middlewarePriority is used for sorting, not your version.
```

**Comment by DarkGhostHunter** [comment]
> Instead I believe this use statement should be `use Illuminate\Contracts\Http\Kernel` after which the `app->make()` call will resolve to `app/Http/Kernel`.

That was my suspicion. I pushed a fix.

**Comment by lphilps** [comment]
That's great many thanks!

I see you made the fix in the 2.x branch and published a new release, but your Two Factor package, which is what I'm using, currently depends on the 1.x version of Meta.  Would it be possible to backport this fix to the 1.x branch, or update Two Factor to use the 2x version of Meta?

Sorry to be a pain.

**Comment by DarkGhostHunter** [comment]
@lphilps Instead of that I will update TwoFactor to use the new Meta version, which separates testing helpers into a dev-package instead of including them in production.

**Comment by lphilps** [comment]
Magnificent.  Thanks!

**Comment by DarkGhostHunter** [comment]
> Magnificent. Thanks!

I had to go into the rabbit hole and make MetaTesting compatible with PHP 8.0 and TwoFactor compatible with 8.0. Three hours. You welcome.

https://github.com/Laragear/TwoFactor/releases/tag/v1.2.1

**Comment by lphilps** [comment]
That's fantastic.  Very much appreciated!
